name: expandable_text_floating_link
description: An additional option to link of ExpandingText class
version: 0.0.1
repository: https://github.com/L1ght5p33D/expandable_text_floating_link

environment:
  sdk: '>=2.19.0-139.0.dev <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



